version: '2'
services:

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "xpack.security.enabled=false"
      - "cluster.name=itest"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTICSEARCH_VERSION}
    depends_on:
      - es
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "ELASTICSEARCH_URL=http://es:9200"
      - "xpack.security.enabled=false"
    ports:
      - "5601:5601"

  search-api:
    build:
      context: .
      args:
        ARTIFACT: ./build/libs/search-api.jar
    image: search-api:itest-latest
    depends_on:
      - es
      - kibana
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n -Dspring.profiles.active=test -Xmx500m -Xms500m"
    ports:
      - "5005:5005"
      - "8482:8482"
