availability_zones:
  - sa-east-1a
  - sa-east-1c
security_groups:
  - sg-1a1a037e
  - sg-591b023d
elb:
  access_logging_policy:
    s3_bucket_name: search-sa-east-1
  subnets:
    - subnet-36d5ad52
    - subnet-47586e1e
asg:
  subnets:
    - subnet-30d5ad54
    - subnet-46586e1f
image_id: ami-f13d509d
spot_price: 0.051
secondary_spot_price: 0.051
